# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Scaffold < Formula
  desc "Scaffold is a tool for creating new projects from pre-defined templates."
  homepage ""
  version "0.0.91"
  license "MIT"

  depends_on "git"
  depends_on "go" => :optional

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/hay-kot/scaffold/releases/download/v0.0.91/scaffold_Darwin_x86_64.tar.gz"
      sha256 "bbce9b0125b7df88d330ecd3dbd48527e02b3022f4f8b0a17ac5afd63db55c17"

      def install
        bin.install "scaffold"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/hay-kot/scaffold/releases/download/v0.0.91/scaffold_Darwin_arm64.tar.gz"
      sha256 "bb91806d78c546244b316864e80c43e62f1cd5c872da7549a5a412d428163b1d"

      def install
        bin.install "scaffold"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/hay-kot/scaffold/releases/download/v0.0.91/scaffold_Linux_x86_64.tar.gz"
      sha256 "a191d8c3487fdd949ff824ac2a72febfffe213e0853af60e04f9a8730bc160ea"

      def install
        bin.install "scaffold"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/hay-kot/scaffold/releases/download/v0.0.91/scaffold_Linux_arm64.tar.gz"
      sha256 "4a2c5d06616debf803747d2671f6a94f667e8e5217ffdebe68911b051b72d6e6"

      def install
        bin.install "scaffold"
      end
    end
  end

  test do
    system "#{bin}/scaffold version"
  end
end
