# This file was generated by GoReleaser. DO NOT EDIT.
cask "scaffold" do
  desc "Scaffold is a tool for creating new projects from pre-defined templates."
  homepage "https://hay-kot.github.io/scaffold/"
  version "0.10.0"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "scaffold"
  depends_on formula: [
      "git",
      "go",
    ]

  on_macos do
    on_intel do
      url "https://github.com/hay-kot/scaffold/releases/download/v0.10.0/scaffold_Darwin_x86_64.tar.gz"
      sha256 "2a0131356c423f38a9af0fa1a5b2a02ce071abc111ab68679ad9f01e99309083"
    end
    on_arm do
      url "https://github.com/hay-kot/scaffold/releases/download/v0.10.0/scaffold_Darwin_arm64.tar.gz"
      sha256 "f5ce3c77ef9907081df6bba9f8a98fba967015e88767b462cbb5cfd6f306f820"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/hay-kot/scaffold/releases/download/v0.10.0/scaffold_Linux_x86_64.tar.gz"
      sha256 "44add232308f0ca9cb145d929c6eface7f9635bb4f7797e8551f8a7e97fe0eea"
    end
    on_arm do
      url "https://github.com/hay-kot/scaffold/releases/download/v0.10.0/scaffold_Linux_arm64.tar.gz"
      sha256 "293e0fc4e10f48b47ba32f4ea6cb6ba561a1c6bf4499db6b3159f580bd6e3381"
    end
  end

  # No zap stanza required
end
