# This file was generated by GoReleaser. DO NOT EDIT.
cask "scaffold" do
  desc "Scaffold is a tool for creating new projects from pre-defined templates."
  homepage "https://hay-kot.github.io/scaffold/"
  version "0.9.0"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "scaffold"
  depends_on formula: [
      "git",
      "go",
    ]

  on_macos do
    on_intel do
      url "https://github.com/hay-kot/scaffold/releases/download/v0.9.0/scaffold_Darwin_x86_64.tar.gz"
      sha256 "c23b7c4aae95254ea41d29578b3585b224411cc0ff4a05b8697e7d50ed4a02c9"
    end
    on_arm do
      url "https://github.com/hay-kot/scaffold/releases/download/v0.9.0/scaffold_Darwin_arm64.tar.gz"
      sha256 "540ba17a24c4d3ca126658eb0c00929326b45cabd41a7a3406b4e38db06a7d43"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/hay-kot/scaffold/releases/download/v0.9.0/scaffold_Linux_x86_64.tar.gz"
      sha256 "f60c0500faf9dbeba4f17bfb28f1436a7d154de233974a4166df0f69fc88c5b5"
    end
    on_arm do
      url "https://github.com/hay-kot/scaffold/releases/download/v0.9.0/scaffold_Linux_arm64.tar.gz"
      sha256 "bd008202f201a31a5d5941b0109e8abda35045297c18eb4373335d91b611bc2d"
    end
  end

  # No zap stanza required
end
