# This file was generated by GoReleaser. DO NOT EDIT.
cask "scaffold" do
  name "scaffold"
  desc "Scaffold is a tool for creating new projects from pre-defined templates."
  homepage "https://hay-kot.github.io/scaffold/"
  version "0.13.1"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "scaffold"
  depends_on formula: [
      "git",
      "go",
    ]

  on_macos do
    on_intel do
      url "https://github.com/hay-kot/scaffold/releases/download/v#{version}/scaffold_Darwin_x86_64.tar.gz"
      sha256 "4396181516897f98b910dfefeafa763df19140d98da02254133ccfca21fac59f"
    end
    on_arm do
      url "https://github.com/hay-kot/scaffold/releases/download/v#{version}/scaffold_Darwin_arm64.tar.gz"
      sha256 "a12fc97aa8264a306dc7429c3a7f5d2206847ba7e83cd482b76f66633d5d9864"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/hay-kot/scaffold/releases/download/v#{version}/scaffold_Linux_x86_64.tar.gz"
      sha256 "9d78d259b5644dd27293e6b221aeccc4966ad185eeb042174bce137f9086c1ac"
    end
    on_arm do
      url "https://github.com/hay-kot/scaffold/releases/download/v#{version}/scaffold_Linux_arm64.tar.gz"
      sha256 "34b021b3521b91d8dd54a9184e60d7902435a99a1a157354eef8f8548a671455"
    end
  end

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/scaffold"]
    end
  end

  # No zap stanza required
end
